version: '3'
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
  moodle:
    image: registry.gitlab.com/dockereabc/dockerfiles:${TAG}
    volumes:
      - ./local/example:/var/www/html/local/example
      - ./theme/cursoscenedi33:/var/www/html/theme/cursoscenedi33
    ports:
      - '${MOODLEPORT}:80'
    environment:
      XDEBUG_CONFIG: $XDEBUG_CONFIG
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      DBHOST: $DBHOST
      MYSQL_DATABASE: $MYSQL_DATABASE
      WWWROOT: $WWWROOT
  adminer:
    image: adminer
    ports:
      - '${ADMINERPORT}:8080'
